apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}-data
  labels:
    app: {{ .Values.name }}
    {{- if .Values.persistence.extraLabels }}
    {{- toYaml .Values.persistence.extraLabels | nindent 4 }}
    {{- end }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  volumeMode: Filesystem
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClass }}
  hostPath:
    path: {{ .Values.persistence.path }}
    type: DirectoryOrCreate