{{- if .Values.deploy }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.rbac.name }}
  namespace: {{ .Release.Namespace | quote }}
rules:
  # Grant full control over ALL resources within this namespace
  # This is a lot, but is needed for Dragonfly to be able to manage Helm releases.
  - apiGroups: ["*"] # Includes core (""), tinkerbell.org, apps, batch, etc.
    resources: ["*"] # Includes services, secrets, pods, workflows, hardware, etc.
    verbs: ["*"]     # Includes get, list, watch, create, update, patch, delete, etc.
{{- end }}
