{{- if .Values.deploy }}
{{- $roleType := .Values.rbac.type }}
{{- if .Values.global }}
{{- $roleType = coalesce .Values.global.rbac.type .Values.rbac.type }}
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ $roleType }}
metadata:
  name: {{ .Values.rbac.name }}
  {{- if eq $roleType "Role" }}
  namespace: {{ .Release.Namespace | quote }}
  {{- end }}
rules:
  # Grant full control over ALL resources within this namespace
  # This is a lot, but is needed for Dragonfly to be able to manage Helm releases.
  - apiGroups: ["*"] # Includes core (""), tinkerbell.org, apps, batch, etc.
    resources: ["*"] # Includes services, secrets, pods, workflows, hardware, etc.
    verbs: ["*"]     # Includes get, list, watch, create, update, patch, delete, etc.
{{- end }}
