---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-data
  namespace: {{ .Release.Namespace | quote }}
spec:
  accessModes:
    {{- toYaml .Values.localPersistentVolume.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.localPersistentVolume.size }}
  storageClassName: {{ .Values.localPersistentVolume.storageClassName }}
  selector:
    matchLabels:
      app: {{ .Values.name }}