---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-data
  namespace: {{ .Release.Namespace | quote }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
  volumeMode: Filesystem
  localPersistentVolume:
    storageClassName: local-storage
    path: /var/lib/dragonfly
    name: dragonfly-data
    accessModes:
      - ReadWriteMany
    size: 20Gi
    extraLabels: {}