---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  serviceName: {{ .Values.name }}
  replicas: 1 # No HA support via SQLite, will later add PostgreSQL
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: DRAGONFLY_BASE_URL
              value: "http://{{ .Values.global.publicIP }}:{{ .Values.service.port }}"
          volumeMounts:
            - name: {{ .Values.name }}-data
              mountPath: /var/lib/dragonfly
          ports:
            - containerPort: {{ .Values.service.port }}
              name: {{ .Values.deployment.portName }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          workingDir: /var/lib/dragonfly
      volumes:
        - name: {{ .Values.name }}-data
          persistentVolumeClaim:
            claimName: {{ .Values.name }}-data
